import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Crousel from "./components/crousal";
import Card from "react-bootstrap/Card";
import Button from "react-bootstrap/Button";
import FeaturedList from "./featured";
import FavoriteList from "./favorite";

export default function Home(props) {
  const [movies, setMovies] = useState(props.data);
  const [src, setSrc] = useState(
    "https://m.media-amazon.com/images/M/MV5BOTk3MDNhODEtMWYyMC00NmVjLTg3NzgtNjI1MzA4ZmVhMjE2XkEyXkFqcGdeQXVyNTkzNDQ4ODc@._V1_SX300.jpg"
  );
  const [favoriteData, setFavoriteData] = useState([]);
  const [check, setCheck] = useState(false);

  const favdata = () => {
    var getdata = JSON.parse(localStorage.getItem("favs"));

    if (getdata) {
      if (getdata.length < 1) return;

      setFavoriteData(getdata);
      console.log(favoriteData);
      DynamicFavData.style.display = "block";
      setCheck(true);
      // document
      //   .getElementById("scrolltofav")
      //   .scrollIntoView({ behavior: "smooth" });
    }
  };
  useEffect(() => {
    favdata();
  }, []);

  return (
    <>
      <Head>
        <title>HEALTHFLIX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script> */}
      </Head>
      <main className={styles.main}>
        {/* <p className={styles.cardp}></p> */}
        {/* <p className={styles.cardp}></p> */}

        <div
          className={`${styles.font} ${styles.ccenter}`}
          style={{ display: "flex", flexDirection: "column" }}
        >
          {/* <lottie-player
            style={{
              height: "8rem",
            }}
            src="https://assets8.lottiefiles.com/packages/lf20_cbrbre30.json"
            background="transparent"
            speed="1"
            // loop
            autoplay
          ></lottie-player> */}
          <h2 className={styles.greet}>Bem-vindo a</h2>
          <div
            className={`${styles.font} ${styles.thirteen}`}
            style={{ display: "flex", flexDirection: "column" }}
          >
            <h2 className={styles.typewriter}>HEALTHFLIX</h2>
          </div>
          {/* <Button
            variant="primary"
            onClick={favdata}
            style={{
              zIndex: "4",
            }}
          >
            Go to Favorites
          </Button> */}
        </div>
        <p className={styles.cardp}>
         Alguns filmes que você pode gostar estão aqui, role para baixo!
        </p>
      </main>
      {/* <Crousel src={src} movies={featured} /> */}

      {/* Featured */}
      <FeaturedList />

      {/* Favorites */}
      <FavoriteList check={check} favoriteData={favoriteData} />

    </>
  );
}

//https://cdn.ggcc8.com//movies/disk3/disk3_2/Zakir%20Khan-%20Tathastu.mp4
